In [26]:
import math
fac=math.factorial(12)
print(fac)

sqr=math.sqrt(25)
print(sqr)

great=math.gcd(15)
print(great)

const=math.pi
print(const)

loga=math.log2(10)
print(loga)

power=math.pow(2,3)
print(power)

ceil=math.ceil(9.4)
print(ceil)

sin=math.sin(30)
print(sin)

absolute=abs(-45)
print(absolute)

exp=math.exp(2)
print(exp)


479001600
5.0
15
3.141592653589793
3.321928094887362
8.0
10
-0.9880316240928618
45
7.38905609893065


In [27]:
import pandas as pd
import numpy as np
ages=np.array([12,20,35])
series=pd.Series(ages)
print(series)

0    12
1    20
2    35
dtype: int64


# New section

In [30]:
import pandas as pd
import numpy as np
ser=pd.Series(ages,index=['ram','sita','hanuman'])
print(ser)

ram        12
sita       20
hanuman    35
dtype: int64


In [37]:
import pandas as pd
import numpy as np
dataf=pd.DataFrame([['Ram',10,'CSE'],['Sita',20,'ETB'],['Lakhman',30,'MTB']],columns=['Name','Age','Ads'])
print(dataf)
erp=dataf.set_index('Name')
print(erp)

      Name  Age  Ads
0      Ram   10  CSE
1     Sita   20  ETB
2  Lakhman   30  MTB
         Age  Ads
Name             
Ram       10  CSE
Sita      20  ETB
Lakhman   30  MTB


In [38]:
import numpy as np
list=[2,4,6,8,10,12,14,16]
arr=np.array(list)
print(arr)
mean=np.mean(arr)
print(mean)
median=np.median(arr)
print(median)
std=np.std(arr)
print(std)
reshape=arr.reshape(2,4)
print(reshape)
sqrt=np.sqrt(arr)
print(sqrt)
max=np.argmax(arr)
print(max)
narr=arr[arr>8]
print(narr)

[ 2  4  6  8 10 12 14 16]
9.0
9.0
4.58257569495584
[[ 2  4  6  8]
 [10 12 14 16]]
[1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162
 3.74165739 4.        ]
7
[10 12 14 16]


In [47]:
import pandas as pd
import numpy as np
dataf=pd.DataFrame([['Alice',28,'HR',50000],['Bob',22,'Engineering',60000],['Charlie',35,'HR',55000],['David',30,'Engineering',62000],['Eve',25,'Finance',45000]],columns=['Name','Age','Dept','Salary'])
print(dataf)

avg_salary = dataf['Salary'].mean()
print("Average Salary of employees:", avg_salary)

max_age_engineering = dataf[dataf['Dept'] == 'Engineering']['Age'].max()
print("Maximum age in Engineering department:", max_age_engineering)

high_salary_names = dataf[dataf['Salary'] > 50000]['Name']
print("Employees with salary greater than 50000:\n", high_salary_names)

dataf.loc[len(dataf)] = ['Frank', 40, 'Finance', 55000]
print(dataf)

dataf=dataf[dataf['Name'] != 'Eve']
print(dataf)

      Name  Age         Dept  Salary
0    Alice   28           HR   50000
1      Bob   22  Engineering   60000
2  Charlie   35           HR   55000
3    David   30  Engineering   62000
4      Eve   25      Finance   45000
Average Salary of employees: 54400.0
Maximum age in Engineering department: 30
Employees with salary greater than 50000:
 1        Bob
2    Charlie
3      David
Name: Name, dtype: object
      Name  Age         Dept  Salary
0    Alice   28           HR   50000
1      Bob   22  Engineering   60000
2  Charlie   35           HR   55000
3    David   30  Engineering   62000
4      Eve   25      Finance   45000
5    Frank   40      Finance   55000
      Name  Age         Dept  Salary
0    Alice   28           HR   50000
1      Bob   22  Engineering   60000
2  Charlie   35           HR   55000
3    David   30  Engineering   62000
5    Frank   40      Finance   55000
